

SELECT * FROM INFORMATION_SCHEMA.COLUMNS C 
	WHERE 
	TABLE_NAME = 'campos' 


				SELECT * FROM INFORMATION_SCHEMA.COLUMNS C 
			  WHERE 
				TABLE_NAME = 'teste' 
				AND TABLE_SCHEMA = 'dbAgencia' 


				SELECT * FROM INFORMATION_SCHEMA.COLUMNS C 
  WHERE 
    TABLE_NAME = 'BAIRRO' 
	AND TABLE_CATALOG =  'dbAgencia'
    AND TABLE_SCHEMA = 'dbo' 
    AND COLUMN_NAME = 'IDBAIRRO' 
    AND DATA_TYPE = 'INT' 
    AND CHARACTER_MAXIMUM_LENGTH = NULL 